name: Python CI

on:
  push:
    branches:
      - master  # Or the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: List files in the repo  # Debugging step to list files
      run: ls -R

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pip-tools
        pip-compile --output-file=requirements.txt ./requirements.txt  # Use relative path if required
        pip install -r requirements.txt
