name: Python Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install pip version 23.1.2
      run: |
        pip install --upgrade pip==23.1.2

    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt

    - name: Run tests
      run: |
        # Your test command here
        python -m unittest discover tests/
