name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest  # or whichever runner you prefer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust based on the Python version you are using

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt  # Ensures the dependencies are installed without cache to avoid issues
          
      - name: Run tests (or any other steps in your workflow)
        run: |
          # Run your tests or deployment steps here
          pytest  # Example: you can replace it with your testing or deployment steps
