name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest  # Or another OS depending on your environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ensure the version matches your project's Python version

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt  # Install from updated requirements.txt

      - name: Run tests (optional)
        run: |
          pytest  # Or your specific tests/steps
