name: Python Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Check Python version
      run: python --version

    - name: Clear pip cache
      run: pip cache purge

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Run tests
      run: |
        # Add your test run command here
        python -m unittest discover tests/
