name: Python CI

on:
  push:
    branches:
      - master  # Or the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest  # Choose your runner OS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Adjust as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Replace with your testing command (e.g., pytest)
          python -m unittest discover
