name: Python CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3.7 from deadsnakes PPA
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install -y python3.7 python3.7-distutils python3-pip
          python3.7 -m pip install --upgrade "pip<24.1"

      - name: Set up Python environment
        run: |
          python3.7 -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python3.7 -m unittest discover
