name: Python CI

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  workflow_dispatch:  # Allow manual trigger via GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: List files in the repo  # Debugging step to list files
      run: ls -R

    - name: Install pip-tools
      run: |
        pip install --upgrade pip
        pip install pip-tools

    - name: Compile the requirements and generate a locked, conflict-free requirements.txt
      run: |
        pip-compile --output-file=requirements.txt ./requirements.txt  # Path to your original requirements file
        cat requirements.txt  # Debugging step to ensure correct requirements are generated

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
