name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest  # Or another OS depending on your environment

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python (ensure version matches your project's version)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ensure this matches your desired Python version (e.g., 3.8)

      # Install pip version that works with the packages
      - name: Install pip version 23.3.1 (to avoid metadata issues)
        run: |
          python -m pip install --upgrade pip==23.3.1  # Pin pip version

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt  # Install from updated requirements.txt

      # Optionally, print Python version and installed packages to debug if needed
      - name: Show Python version and installed packages
        run: |
          python --version
          pip freeze

      # Run tests (optional)
      - name: Run tests (optional)
        run: |
          pytest  # Or your specific test commands
